// Vendored verbatim from protoc-gen-mcp output:
//   the-protobuf-project/mcp @ examples/proto/generated/rust/counter/v1/counter_service.mcp.rs
//
// It is a fixture, not hand-written code: it must stay byte-identical to what the plugin
// emits, or the test stops proving anything about real generated output. Only the trailing
// serve_* helpers are dropped — those bind their own listener, which is the job the runtime
// takes over, and they are what this test exists to replace.

// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp v1.7.1-0.20260818043044-6fa3c9d0f37d+dirty
// Authors: The Protobuf Project - Open Source 2026
// source: counter/v1/counter_service.proto

use async_trait::async_trait;
use rmcp::{
    ErrorData as McpError, RoleServer, ServerHandler, ServiceExt,
    model::*,
    service::{Peer, RequestContext},
};
use serde_json::{self, Value, json};
use std::sync::Arc;

fn make_tool(
    name: &str,
    description: &str,
    schema_json: &str,
    output_schema_json: &str,
    annotations: Value,
    title: &str,
    icons: Value,
) -> Tool {
    let mut tool = json!({
        "name": name, "description": description,
        "inputSchema": serde_json::from_str::<Value>(schema_json).unwrap(),
        "outputSchema": serde_json::from_str::<Value>(output_schema_json).unwrap(),
    });
    // A hint the proto does not state stays absent: to a client, "unknown" is
    // not the same as "false".
    if !annotations.is_null() {
        tool["annotations"] = annotations;
    }
    if !title.is_empty() {
        tool["title"] = json!(title);
    }
    if !icons.is_null() {
        tool["icons"] = icons;
    }
    serde_json::from_value(tool).expect("generated tool schema must be valid")
}

fn make_tool_with_app_meta(
    name: &str,
    description: &str,
    schema_json: &str,
    output_schema_json: &str,
    annotations: Value,
    title: &str,
    icons: Value,
    app_resource_uri: &str,
) -> Tool {
    let mut tool = json!({
        "name": name, "description": description,
        "inputSchema": serde_json::from_str::<Value>(schema_json).unwrap(),
        "outputSchema": serde_json::from_str::<Value>(output_schema_json).unwrap(),
        "_meta": { "ui": { "resourceUri": app_resource_uri } }
    });
    if !annotations.is_null() {
        tool["annotations"] = annotations;
    }
    if !title.is_empty() {
        tool["title"] = json!(title);
    }
    if !icons.is_null() {
        tool["icons"] = icons;
    }
    serde_json::from_value(tool).expect("generated tool schema must be valid")
}

fn app_resource_uri(service_name: &str) -> String {
    format!("ui://{}/app.html", service_name.to_lowercase())
}

/// Sends MCP progress notifications for one tool call.
///
/// A server-streaming RPC reports incremental progress through this. When the
/// client sent no progressToken there is nothing to correlate a notification
/// with, so every send is a no-op and an implementation never has to check.
///
/// The `Default` sink is exactly that inert one, which is what a unit test for a
/// streaming RPC wants.
#[derive(Clone, Default)]
pub struct McpProgressSink {
    peer: Option<Peer<RoleServer>>,
    token: Option<ProgressToken>,
}

impl McpProgressSink {
    fn new(peer: Option<Peer<RoleServer>>, token: Option<ProgressToken>) -> Self {
        Self { peer, token }
    }

    /// Reports progress. `total` is the expected final value when known.
    pub async fn send(&self, progress: f64, total: Option<f64>, message: Option<String>) {
        let (Some(peer), Some(token)) = (self.peer.as_ref(), self.token.as_ref()) else {
            return;
        };
        // ProgressNotificationParam is #[non_exhaustive], so it is built through
        // its constructor rather than a struct literal.
        let mut param = ProgressNotificationParam::new(token.clone(), progress);
        if let Some(total) = total {
            param = param.with_total(total);
        }
        if let Some(message) = message {
            param = param.with_message(message);
        }
        // A dropped client should not fail the tool call it is no longer watching.
        let _ = peer.notify_progress(param).await;
    }
}

fn default_app_html(app_name: &str, version: &str, description: &str) -> String {
    format!(
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>{app_name}</title></head><body><h1>{app_name}</h1><p>v{version}</p><p>{description}</p><p>This is a generated MCP App placeholder. Replace this resource with your own UI.</p></body></html>"
    )
}

const COUNTER_SERVICE__COUNT_SCHEMA_JSON: &str = r##"{"description":"Counts from 0 up to the given number. Sends progress updates as it counts. Use with progressToken in _meta for progress notifications.","properties":{"to":{"description":"Count from 0 up to this number. Progress updates are sent each step.","examples":["5","10"],"type":"integer"}},"required":[],"type":"object"}"##;
const COUNTER_SERVICE__COUNT_OUTPUT_SCHEMA_JSON: &str =
    r##"{"properties":{"count":{"type":"integer"}},"required":[],"type":"object"}"##;

#[async_trait]
pub trait CounterServiceMcpServer: Send + Sync + 'static {
    /// Server-streaming RPC: report incremental progress through `progress`,
    /// then return the final result.
    async fn count(
        &self,
        args: Value,
        progress: McpProgressSink,
    ) -> std::result::Result<Value, McpError>;
}

pub struct CounterServiceMcpHandler<T: CounterServiceMcpServer> {
    inner: Arc<T>,
}

impl<T: CounterServiceMcpServer> Clone for CounterServiceMcpHandler<T> {
    fn clone(&self) -> Self {
        Self {
            inner: Arc::clone(&self.inner),
        }
    }
}

impl<T: CounterServiceMcpServer> CounterServiceMcpHandler<T> {
    pub fn new(svc: T) -> Self {
        Self {
            inner: Arc::new(svc),
        }
    }

    pub fn tools() -> Vec<Tool> {
        let app_uri = app_resource_uri("CounterService");
        vec![make_tool_with_app_meta(
            "counter_service-count_v1",
            "Counts from 0 up to the given number. Sends progress updates as it counts. Use with progressToken in _meta for progress notifications.",
            COUNTER_SERVICE__COUNT_SCHEMA_JSON,
            COUNTER_SERVICE__COUNT_OUTPUT_SCHEMA_JSON,
            Value::Null,
            "",
            Value::Null,
            &app_uri,
        )]
    }

    pub fn resources() -> Vec<Resource> {
        vec![
            serde_json::from_value(json!({
                "uri": app_resource_uri("CounterService"),
                "name": "Counter App",
                "mimeType": "text/html"
            }))
            .expect("generated app resource must be valid"),
        ]
    }

    pub fn resource_templates() -> Vec<ResourceTemplate> {
        vec![]
    }
}

impl<T: CounterServiceMcpServer> ServerHandler for CounterServiceMcpHandler<T> {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new("CounterService", "0.1.0"))
    }

    async fn list_tools(
        &self,
        _: Option<PaginatedRequestParams>,
        _: RequestContext<RoleServer>,
    ) -> std::result::Result<ListToolsResult, McpError> {
        Ok(ListToolsResult::with_all_items(Self::tools()))
    }
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> std::result::Result<CallToolResponse, McpError> {
        let args = request
            .arguments
            .map_or_else(|| Value::Object(Default::default()), Value::Object);
        match request.name.as_ref() {
            "counter_service-count_v1" => {
                // Progress notifications correlate through the token the client
                // sent in _meta; without one the sink silently does nothing.
                let sink = McpProgressSink::new(
                    Some(context.peer.clone()),
                    context.meta.get_progress_token(),
                );
                let result = self.inner.count(args, sink).await?;
                let text = serde_json::to_string(&result).map_err(|e| {
                    McpError::internal_error(format!("serialize response: {e}"), None)
                })?;
                Ok(CallToolResult::success(vec![ContentBlock::text(text)]).into())
            }
            _ => Err(McpError::internal_error(
                format!("unknown tool: {}", request.name),
                None,
            )),
        }
    }

    async fn list_resources(
        &self,
        _: Option<PaginatedRequestParams>,
        _: RequestContext<RoleServer>,
    ) -> std::result::Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult::with_all_items(Self::resources()))
    }

    async fn list_resource_templates(
        &self,
        _: Option<PaginatedRequestParams>,
        _: RequestContext<RoleServer>,
    ) -> std::result::Result<ListResourceTemplatesResult, McpError> {
        Ok(ListResourceTemplatesResult::with_all_items(
            Self::resource_templates(),
        ))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _: RequestContext<RoleServer>,
    ) -> std::result::Result<ReadResourceResponse, McpError> {
        let app_uri = app_resource_uri("CounterService");
        if request.uri == app_uri {
            let html = default_app_html(
                "Counter App",
                "1.0.0",
                "A simple counter that streams progress as it counts",
            );
            return Ok(ReadResourceResult::new(vec![
                ResourceContents::text(html, request.uri).with_mime_type("text/html"),
            ])
            .into());
        }
        Ok(ReadResourceResult::new(vec![ResourceContents::text("{}", request.uri)]).into())
    }
}

pub const COUNTER_SERVICE_MCP_DEFAULT_BASE_PATH: &str = "/counter/v1/counterservice/mcp";

pub struct CounterServiceMcpTransportConfig {
    pub transport: String,
    pub host: String,
    pub port: u16,
    pub base_path: String,
}

impl Default for CounterServiceMcpTransportConfig {
    fn default() -> Self {
        Self {
            transport: "streamable-http".into(),
            host: "0.0.0.0".into(),
            port: 8080,
            base_path: COUNTER_SERVICE_MCP_DEFAULT_BASE_PATH.into(),
        }
    }
}
